version: "3"

networks:
  api: {}

volumes:
  db-data: {}

services:
  db:
    environment:
      POSTGRES_DB: db
      POSTGRES_HOST_AUTH_METHOD: trust
    image: postgres:12.8-alpine
    command: postgres -c 'max_connections=200'
    ports:
      - "5439:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
